name: TaskFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Installer les dépendances
        run: pip install -r requirements.txt
      - name: Lancer les tests
        run: python -m pytest test_app.py -v

  build:
    name: Build Docker
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image Docker
        run: docker build -t taskflow:${{ github.sha }} .

  security:
    name: Scan Trivy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image Docker
        run: docker build -t taskflow:${{ github.sha }} .
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'taskflow:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
